#include "ch.h"
#include "hal.h"
#include "halStm32F1.h"

#define NOF_MASTER_DIG_IN       24
#define NOF_MASTER_DIG_OUT      0
#define NOF_SLAVE_DIG_IN        4
#define NOF_SLAVE_DIG_OUT       10
#define NOF_ANALOG_IN           16

//static adcsample_t samples_buf[NOF_SLAVE_DIG_OUT];



gpio_config_s MASTER_IN[]={
  {GPIOA,0,PAL_MODE_INPUT_PULLUP},
  {GPIOA,1,PAL_MODE_INPUT_PULLUP},
  {GPIOA,2,PAL_MODE_INPUT_PULLUP},
  {GPIOA,3,PAL_MODE_INPUT_PULLUP},
  {GPIOA,4,PAL_MODE_INPUT_PULLUP},
  {GPIOA,5,PAL_MODE_INPUT_PULLUP},
  {GPIOA,6,PAL_MODE_INPUT_PULLUP},
  {GPIOA,7,PAL_MODE_INPUT_PULLUP},
  {GPIOC,0,PAL_MODE_INPUT_PULLUP},
  {GPIOC,1,PAL_MODE_INPUT_PULLUP},
  {GPIOC,2,PAL_MODE_INPUT_PULLUP},
  {GPIOC,3,PAL_MODE_INPUT_PULLUP},
  {GPIOC,4,PAL_MODE_INPUT_PULLUP},
  {GPIOC,5,PAL_MODE_INPUT_PULLUP},
  {GPIOC,6,PAL_MODE_INPUT_PULLUP},
  {GPIOC,7,PAL_MODE_INPUT_PULLUP},
  {GPIOC,8,PAL_MODE_INPUT_PULLUP},
  {GPIOC,9,PAL_MODE_INPUT_PULLUP},
  {GPIOC,10,PAL_MODE_INPUT_PULLUP},
  {GPIOC,11,PAL_MODE_INPUT_PULLUP},
  {GPIOC,12,PAL_MODE_INPUT_PULLUP},
  {GPIOC,13,PAL_MODE_INPUT_PULLUP},
  {GPIOB,0,PAL_MODE_INPUT_PULLUP},
  {GPIOB,1,PAL_MODE_INPUT_PULLUP},
  
};

gpio_config_s MASTER_SLAVE_ID_IN[]={
  {GPIOB,15,PAL_MODE_INPUT_PULLUP},
  {GPIOB,14,PAL_MODE_INPUT_PULLUP},
  {GPIOB,13,PAL_MODE_INPUT_PULLUP},
  {GPIOB,12,PAL_MODE_INPUT_PULLUP},
  {GPIOB,11,PAL_MODE_INPUT_PULLUP},
  {GPIOB,10,PAL_MODE_INPUT_PULLUP},
};


gpio_control_s MASTER_CONTROL[128];

gpio_config_s LED_OUT[]={
  {GPIOA,8,PAL_MODE_OUTPUT_PUSHPULL}
};

gpio_config_s SLAVE_IN[]={
  {GPIOC,10,PAL_MODE_INPUT_PULLUP},
  {GPIOC,11,PAL_MODE_INPUT_PULLUP},
  {GPIOC,12,PAL_MODE_INPUT_PULLUP},
  {GPIOC,13,PAL_MODE_INPUT_PULLUP},
};
gpio_config_s SLAVE_OUT[]={
  {GPIOC,0,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,1,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,2,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,3,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,4,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,5,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,6,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,7,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,8,PAL_MODE_OUTPUT_PUSHPULL},
  {GPIOC,9,PAL_MODE_OUTPUT_PUSHPULL},
};

gpio_config_s SLAVE_ANA_SENSE[]={
  {GPIOA,0,PAL_MODE_INPUT_ANALOG},
  {GPIOA,1,PAL_MODE_INPUT_ANALOG},
  {GPIOA,2,PAL_MODE_INPUT_ANALOG},
  {GPIOA,3,PAL_MODE_INPUT_ANALOG},
  {GPIOA,4,PAL_MODE_INPUT_ANALOG},
  {GPIOA,5,PAL_MODE_INPUT_ANALOG},
  {GPIOA,6,PAL_MODE_INPUT_ANALOG},
  {GPIOA,7,PAL_MODE_INPUT_ANALOG},
  {GPIOB,0,PAL_MODE_INPUT_ANALOG},
  {GPIOB,1,PAL_MODE_INPUT_ANALOG},
};
  
gpio_config_s peripheral_config[]={
  {GPIOA,11,PAL_MODE_INPUT_PULLUP},     // CAN_TX
  {GPIOA,12,PAL_MODE_STM32_ALTERNATE_PUSHPULL}, // CAN_RX
  {GPIOB,6,PAL_MODE_STM32_ALTERNATE_OPENDRAIN}, // I2C_SCL
  {GPIOB,7,PAL_MODE_STM32_ALTERNATE_OPENDRAIN}, // I2C_SDA
};


void halJ1939Init(void)
{
#ifdef USE_MASTER
  halCANMasterInit();
#endif
  
#ifdef USE_SLAVE
  halCANSlaveInit();
#endif
  // todo: start I2C bus for AD5593R
}

void hanStm32F1Init()
{
  int i;
  for(i=0;i<NOF_MASTER_DIG_IN;i++){
    palSetPadMode(MASTER_IN[i].port, MASTER_IN[i].pin,MASTER_IN[i].mode);
  }
  
  for(i=0;i<6;i++){
    palSetPadMode(MASTER_SLAVE_ID_IN[i].port, MASTER_SLAVE_ID_IN[i].pin,MASTER_SLAVE_ID_IN[i].mode);
  }
  
  palSetPadMode(LED_OUT[0].port, LED_OUT[0].pin,LED_OUT[0].mode); 
  
  for(i=0;i<sizeof(peripheral_config)/sizeof(gpio_config_s);i++){
    palSetPadMode(peripheral_config[i].port, peripheral_config[i].pin,peripheral_config[i].mode);
  }
}





